# Generated by Django 4.2.1 on 2023-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='lesson',
        ),
    ]
