# Generated by Django 4.2.1 on 2023-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0002_remove_lead_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lesson',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
