# Generated by Django 4.2.1 on 2023-05-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lesson',
            field=models.CharField(default='default_text', max_length=255),
        ),
    ]
