# Generated by Django 4.2.1 on 2023-06-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='bio',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='goals',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='keyword',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lesson',
            field=models.CharField(default='Empty', max_length=255),
        ),
    ]
