# Generated by Django 4.2.1 on 2023-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0006_alter_lead_bio_alter_lead_goals_alter_lead_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='team_members',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
