# Generated by Django 4.2.1 on 2023-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_lead_brand_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='brand_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_design',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_function',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_packaging',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_quality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
