# Generated by Django 4.2.1 on 2023-06-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0010_alter_lead_contact_person_alter_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='level_exp',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='points',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
