# Generated by Django 4.2.1 on 2023-06-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0011_lead_level_exp_lead_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='level_exp',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='points',
            field=models.CharField(blank=True, default=0, max_length=1000, null=True),
        ),
    ]
